---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: macos-instance
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: ""
    override_command: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /tmp:/tmp:rw,Z
    privileged: false
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_REMOTE_TMP: "/root/.ansible/tmp"
  config_options:
    defaults:
      remote_tmp: /root/.ansible/tmp
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  name: macos
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy