---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/fedora:latest
    pre_build_image: true
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host
  - name: centos
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host
  - name: ubuntu
    image: docker.io/ubuntu:22.04
    pre_build_image: true
    command: "sleep infinity"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp
  config_options:
    defaults:
      remote_tmp: /tmp
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  name: multi-platform
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy