---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/fedora:latest
    pre_build_image: true
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      /run: rw
      /tmp: rw
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp
  config_options:
    defaults:
      remote_tmp: /tmp
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy