---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: simple
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp
  inventory:
    host_vars:
      simple:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
scenario:
  name: simple
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy