---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify directory exists
      ansible.builtin.stat:
        path: "/etc/file_manager"
      register: dir_stat

    - name: Verify file exists
      ansible.builtin.stat:
        path: "/etc/file_manager/test.conf"
      register: file_stat

    - name: Assert directory and file were created
      assert:
        that:
          - dir_stat.stat.exists
          - file_stat.stat.exists